version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: America/Mexico_City
    assignees:
      - "edgarrmondragon"
    commit-message:
      prefix: "ci: "
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
