name: readthedocs/actions
on:
  pull_request:
    types:
      - opened
      - updated

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: edgarrmondragon/actions/preview@use-project-endpoint
        with:
          project-slug: "pep610"
